// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appRoot': string;
  'visuallyHidden': string;
}
export const cssExports: CssExports;
export default cssExports;
